name: Seed TAG Reports on BitTorrent

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5

    - name: Concatenate reports into a single text file
      run: cat reports/* > UltimateRevelation.txt

    - name: Build Docker image
      run: docker build -t bittorrent-seeder .

    - name: Install Transmission and create torrent
      run: |
        docker run --rm -v ${{ github.workspace }}:/downloads bittorrent-seeder bash -c "
          apt-get update && apt-get install -y transmission-cli &&
          transmission-create -o /downloads/UltimateRevelation.torrent /downloads/UltimateRevelation.txt
        "

    - name: Start Transmission daemon and seed torrent
      run: |
        docker run -d --name seeder -v ${{ github.workspace }}:/downloads bittorrent-seeder transmission-daemon -f -t -w /downloads
        
        # Ensure the daemon is up
        sleep 10
        
        # Add torrent to the transmission daemon
        docker exec seeder transmission-remote -a /downloads/UltimateRevelation.torrent
        
        # Tail the logs to keep the container running and see the progress
        docker logs -f seeder
