name: Clone Repository to /wiki

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  clone-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the current repository
      uses: actions/checkout@v2

    - name: Set up the repository
      run: |
        mkdir -p wiki
        cd wiki
        git clone https://github.com/TAGIsNoGame/TAG.wiki.git .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Cloned repository into /wiki"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
