name: Combine Markdown Files

on:
  push:
    branches:
      - master

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find Markdown Files
        run: |
          find . -type f -name '*.md' -exec cat {} + > /tmp/combined.md

      - name: Commit combined file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add /tmp/combined.md
          git commit -m "Combine markdown files"
