name: Check URL Reachability

on:
  workflow_dispatch:

jobs:
  check_url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check URL
      run: |
        response=$(curl -o /dev/null -s -w "%{http_code}\n" https://GitHub.com/StopTAG)
        if [ "$response" -eq 200 ]; then
          echo "URL is reachable and returned 200 OK."
        else
          echo "URL is not reachable or did not return 200 OK. HTTP status: $response"
          exit 1
        fi
