name: Manual Clone and Commit Repository

on:
  workflow_dispatch:

jobs:
  clone-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone MCBCMF/MCBCMassacre repository
        run: git clone https://github.com/MCBCMF/MCBCMassacre.git MCBCMassacre

      - name: Commit changes
        working-directory: ./MCBCMassacre
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Clone MCBCMF/MCBCMassacre repository"
          git push origin master
