name: Rename Directories

on:
  workflow_dispatch:

jobs:
  rename-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rename directories
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -d "wiki" ]; then
            git mv wiki reports
          fi
          if [ -d "wiki_drafts" ]; then
            git mv wiki_drafts report_drafts
          fi
          git commit -m "Rename directories: wiki to reports, wiki_drafts to report_drafts"
          git push
