name: Update Wiki Links

on:
  push:
    branches:
      - main

jobs:
  update-wiki-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete existing /wiki directory if it exists
        run: |
          if [ -d "wiki" ]; then
            rm -rf wiki
          fi

      - name: Copy .md files from /reports to /wiki
        run: |
          mkdir -p wiki
          cp -R reports/*.md wiki/

      - name: Replace text with GitHub wiki links
        run: |
          for file in wiki/*.md; do
            file_name=$(basename "$file" .md)
            search_text=$(echo "$file_name" | sed 's/-/ /g')
            link_text="[[${search_text}|]]"
            # Process the file line by line, skipping lines that start with #
            awk -v search="$search_text" -v replace="$link_text" '
              !/^#/ { gsub(search, replace) }
              { print }
            ' "$file" > tmpfile && mv tmpfile "$file"
          done

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wiki/
          git commit -m "Update wiki links in .md files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
