name: Update Wiki Links

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  update-wiki-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy .md files from /reports to /wiki
        run: |
          mkdir -p wiki
          cp -R reports/*.md wiki/

      - name: Replace text with GitHub wiki links
        run: |
          for file in wiki/*.md; do
            file_name=$(basename "$file" .md)
            search_text=$(echo "$file_name" | sed 's/-/ /g')
            link_text="[[${search_text}|]]"
            sed -i "s/${search_text}/${link_text}/g" "$file"
          done

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add wiki/
          git commit -m "Update wiki links in .md files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Wiki Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          cp -R wiki/* ${{ github.repository }}.wiki/
          cd ${{ github.repository }}.wiki/
          git add .
          git commit -m "Force update wiki with new content"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
